### ISSUE TITLE
Conflict with Oryol

### ISSUE THREAD

**Issue by jreach-dev** [floooh/oryol-imgui#5]
If this is included in fips.yml file and the normal oryol is included, then they conflict. Is there any way to manage this sort of redundancy?

**Comment by floooh** [comment]
Can you describe in more detail what's happening? (error messages you're seeing, etc...)

For an example project which uses both Oryol and oryol-imgui as dependencies you can check out the fips.yml file in the oryol-samples repository:

https://github.com/floooh/oryol-samples/blob/master/fips.yml

(wait, this doesn't seem to directly use Oryol as dependency, I'll add an entry to make it clearer, maybe then I'll also see whether there's a problem)

(added the oryol dependency now and testing... which worked on a fresh checkout, no problems encountered here)

**Comment by jreach-dev** [comment]
I did a fresh checkout and it works. Sorry about the inconvenience! I use your work for a lot of prototyping, thanks!
